// More everyday and eating-out foods (session 13), so someone who logs what they actually ate,
// plan or no plan, finds it: the fast-food chains sold in Egypt, pizza and feteer, Egyptian street
// food and home dishes, bakery, sweets, snacks, drinks and sauces.
//
// Same rules as offplan-foods.js: never used to build or change a plan (offplan: true, no roles).
// Since session 13 they CAN earn points: logged inside a meal that still matches its plan
// (see OFFPLAN_MEAL_MATCH in adherence.js).
//
// Values per 100 g as eaten. Chain-style items are worked out from the chains' published
// nutrition (per item, divided by the item's weight); everything else from USDA FoodData Central
// fast-food, bakery and recipe entries or common Egyptian recipes. Names stay generic ("Big Mac
// style"); brand names people type are search keywords only (SEARCH_KEYWORDS below).
// `unit` is the natural count; `m` adds more measures ([name, plural, grams, half]).

const O = (id, name, ar, cat, kcal, p, c, f, unit, o = {}) => ({
  id, name, ar, cat, kcal, p, c, f, roles: [],
  tags: o.tags ?? [], veg: o.veg ?? false, step: o.step ?? 5, max: o.max ?? 1500,
  portion: null, unit: { g: unit[1], name: unit[0] }, est: true, raw: null, offplan: true,
  measures: o.m ?? [],
});
const M = (name, plural, g, half = false) => [name, plural, g, half];
const V = { veg: true };
const PIZZA = (personal, medium, large) => [M('personal pizza', 'personal pizzas', personal), M('medium pizza', 'medium pizzas', medium), M('large pizza', 'large pizzas', large)];
const FETEER = [M('half feteer', 'half feteers', 300), M('whole feteer', 'whole feteers', 600)];

export const MORE_OFFPLAN_FOODS = [
  // ---------------------------------------------------------------- burger chains
  O('big-mac-style', 'Double burger with special sauce (Big Mac style)', 'بيج ماك', 'fastfood', 251, 11.4, 20.5, 13.7, ['burger', 219], { tags: ['gluten', 'meat', 'dairy', 'egg', 'sesame'] }),
  O('quarter-pounder', 'Quarter-pound cheeseburger (McRoyale style)', 'ماك رويال', 'fastfood', 257, 14.9, 20.8, 12.9, ['burger', 202], { tags: ['gluten', 'meat', 'dairy', 'sesame'] }),
  O('mcchicken-style', 'Crispy chicken burger, fast food (McChicken style)', 'ماك تشيكن', 'fastfood', 280, 9.8, 27.3, 14.7, ['burger', 143], { tags: ['gluten', 'poultry', 'egg'] }),
  O('fish-burger', 'Fish fillet burger (Filet-O-Fish style)', 'برجر سمك فيليه', 'fastfood', 275, 11.3, 27.5, 13.4, ['burger', 142], { tags: ['gluten', 'fish', 'dairy', 'egg'] }),
  O('whopper-style', 'Flame-grilled big burger (Whopper style)', 'وابر', 'fastfood', 244, 10.4, 18.1, 14.8, ['burger', 270], { tags: ['gluten', 'meat', 'egg', 'sesame'] }),
  O('chicken-royale', 'Long crispy chicken sandwich (Chicken Royale style)', 'تشيكن رويال', 'fastfood', 274, 12, 24.4, 13.9, ['sandwich', 209], { tags: ['gluten', 'poultry', 'egg', 'sesame'] }),
  O('zinger', 'Spicy crispy chicken burger (Zinger style)', 'زنجر', 'fastfood', 230, 12, 21, 11, ['burger', 210], { tags: ['gluten', 'poultry', 'egg'] }),
  O('twister', 'Crispy chicken wrap (Twister style)', 'تويستر', 'fastfood', 225, 10, 22, 11, ['wrap', 230], { tags: ['gluten', 'poultry', 'egg'] }),
  O('famous-star', 'Big beef burger with cheese and mayo (Famous Star style)', 'برجر فيمس ستار', 'fastfood', 255, 11, 20, 14.5, ['burger', 260], { tags: ['gluten', 'meat', 'dairy', 'egg', 'sesame'] }),
  O('mushroom-swiss', 'Mushroom and Swiss cheese beef burger', 'برجر مشروم وسويس', 'fastfood', 250, 13.5, 17, 14, ['burger', 260], { tags: ['gluten', 'meat', 'dairy', 'egg'] }),
  O('chicken-burger-grilled', 'Grilled chicken burger', 'برجر فراخ مشوية', 'fastfood', 190, 14, 20, 6, ['burger', 200], { tags: ['gluten', 'poultry', 'egg'] }),
  O('smash-burger', 'Smash burger, double with cheese', 'سماش برجر', 'fastfood', 285, 15, 17, 17.5, ['burger', 230], { tags: ['gluten', 'meat', 'dairy', 'egg'] }),
  O('chicken-burger-cheese', 'Crispy chicken burger with cheese (restaurant)', 'برجر فراخ كرسبي بالجبنة', 'fastfood', 255, 12.5, 22, 13, ['burger', 260], { tags: ['gluten', 'poultry', 'dairy', 'egg'] }),
  O('egg-muffin', 'Egg and cheese breakfast muffin (McMuffin style)', 'إيج ماك مافن', 'fastfood', 226, 12.4, 21.9, 9.5, ['muffin', 137], { tags: ['gluten', 'egg', 'dairy'], ...V }),
  O('hash-brown', 'Hash brown', 'هاش براون', 'fastfood', 264, 1.9, 28, 15, ['piece', 53], V),
  O('apple-pie-ff', 'Fried apple pie (fast food)', 'فطيرة تفاح', 'fastfood', 299, 2.6, 44, 14.3, ['pie', 77], { tags: ['gluten'], ...V }),

  // ---------------------------------------------------------------- fried chicken chains & sides
  O('kfc-original', 'Fried chicken, original recipe (KFC style)', 'فراخ كنتاكي أوريجينال', 'fastfood', 242, 24.2, 6.8, 13, ['piece', 161], { tags: ['gluten', 'poultry', 'egg'], m: [M('small piece (wing or drumstick)', 'small pieces', 75), M('3-piece meal (no sides)', '3-piece meals', 400)] }),
  O('popcorn-chicken', 'Popcorn chicken', 'بوب كورن تشيكن', 'fastfood', 300, 16, 18, 18, ['regular box', 114], { tags: ['gluten', 'poultry', 'egg'], m: [M('large box', 'large boxes', 170)] }),
  O('rizo', 'Spicy rice bowl with crispy chicken (Rizo style)', 'ريزو', 'fastfood', 165, 7, 22, 5.5, ['bowl', 300], { tags: ['gluten', 'poultry'] }),
  O('mashed-potato-gravy', 'Mashed potato with gravy (fast food)', 'بطاطس بيوريه بالجريفي', 'fastfood', 90, 1.6, 13, 3.5, ['cup', 150], { tags: ['dairy', 'gluten'], ...V }),
  O('chicken-wrap-grilled', 'Grilled chicken wrap (fast food)', 'راب فراخ مشوية', 'fastfood', 200, 13, 20, 7.5, ['wrap', 230], { tags: ['gluten', 'poultry'] }),
  O('chicken-wings-bbq', 'Chicken wings, BBQ glazed', 'أجنحة فراخ باربكيو', 'fastfood', 260, 18, 10, 16.5, ['wing', 35], { tags: ['poultry'] }),
  O('fries-curly', 'Curly fries', 'بطاطس كيرلي', 'fastfood', 300, 3.5, 37, 16, ['medium portion', 130], V),
  O('fries-cheese', 'Fries with cheese sauce', 'بطاطس بالجبنة', 'fastfood', 280, 5, 30, 15.5, ['portion', 200], { tags: ['dairy'], ...V }),
  O('potato-wedges', 'Potato wedges, fried', 'بطاطس ودجز', 'fastfood', 230, 3.5, 28, 11.5, ['portion', 150], V),
  O('nuggets-frozen', 'Chicken nuggets, frozen, oven-baked', 'ناجتس فراخ مجمد', 'fastfood', 250, 14, 16, 14, ['nugget', 18], { tags: ['gluten', 'poultry'] }),
  O('chicken-patty-frozen', 'Frozen chicken burger patty, fried', 'برجر فراخ مجمد', 'fastfood', 270, 13, 14, 18, ['patty', 70], { tags: ['gluten', 'poultry'] }),
  O('fish-fingers', 'Fish fingers', 'فيش فينجر', 'fastfood', 230, 12, 22, 10.5, ['finger', 28], { tags: ['gluten', 'fish'] }),
  O('fish-and-chips', 'Fish and chips', 'فيش آند تشيبس', 'fastfood', 220, 9.5, 22, 11, ['portion', 350], { tags: ['gluten', 'fish'] }),

  // ---------------------------------------------------------------- sandwiches, wraps, subs
  O('sub-chicken', 'Chicken sub, 6-inch (Subway style)', 'ساب فراخ', 'fastfood', 145, 10.5, 18.6, 2.7, ['6-inch sub', 220], { tags: ['gluten', 'poultry'], m: [M('footlong', 'footlongs', 440)] }),
  O('sub-tuna', 'Tuna sub, 6-inch', 'ساب تونة', 'fastfood', 210, 9, 18, 11, ['6-inch sub', 230], { tags: ['gluten', 'fish', 'egg'], m: [M('footlong', 'footlongs', 460)] }),
  O('club-sandwich', 'Club sandwich', 'كلوب ساندوتش', 'fastfood', 230, 12, 20, 11, ['sandwich', 250], { tags: ['gluten', 'poultry', 'egg', 'dairy'] }),
  O('grilled-cheese', 'Grilled cheese sandwich', 'ساندوتش جبنة سايحة', 'fastfood', 300, 11, 30, 15, ['sandwich', 130], { tags: ['gluten', 'dairy'], ...V }),
  O('turkey-sandwich', 'Turkey and cheese sandwich', 'ساندوتش تيركي وجبنة', 'fastfood', 220, 12, 24, 8, ['sandwich', 180], { tags: ['gluten', 'poultry', 'dairy'] }),
  O('panini-chicken', 'Chicken panini', 'بانيني فراخ', 'fastfood', 240, 13, 24, 10, ['panini', 220], { tags: ['gluten', 'poultry', 'dairy'] }),
  O('chicken-pane-sandwich', 'Chicken pané sandwich', 'ساندوتش بانيه', 'fastfood', 270, 12, 27, 12.5, ['sandwich', 200], { tags: ['gluten', 'poultry', 'egg'] }),
  O('kofta-sandwich', 'Kofta sandwich', 'ساندوتش كفتة', 'fastfood', 250, 12, 22, 13, ['sandwich', 180], { tags: ['gluten', 'meat'] }),
  O('fish-sandwich', 'Fried fish sandwich', 'ساندوتش سمك', 'fastfood', 250, 11, 27, 11, ['sandwich', 200], { tags: ['gluten', 'fish'] }),
  O('shrimp-sandwich', 'Fried shrimp sandwich', 'ساندوتش جمبري', 'fastfood', 245, 10, 28, 10, ['sandwich', 200], { tags: ['gluten', 'seafood'] }),
  O('street-burger', 'Street burger sandwich', 'ساندوتش برجر', 'fastfood', 260, 11, 25, 13, ['sandwich', 170], { tags: ['gluten', 'meat'] }),
  O('basterma-eggs', 'Eggs with basterma', 'بيض بالبسطرمة', 'meals', 220, 17, 1.5, 16, ['pan (2 eggs)', 150], { tags: ['egg', 'meat'] }),
  O('shawarma-arabi', 'Chicken shawarma arabi (cut, with fries and garlic)', 'شاورما عربي', 'fastfood', 245, 12, 24, 11, ['meal', 350], { tags: ['gluten', 'poultry', 'sesame'] }),
  O('shawarma-saj', 'Chicken shawarma saj', 'شاورما صاج', 'fastfood', 220, 12, 21, 10, ['saj', 300], { tags: ['gluten', 'poultry'] }),
  O('shawarma-fatteh', 'Shawarma fatteh', 'فتة شاورما', 'fastfood', 210, 10, 20, 10, ['bowl', 350], { tags: ['gluten', 'poultry', 'dairy', 'sesame'] }),
  O('crepe-pane', 'Crepe with chicken pané and cheese', 'كريب بانيه', 'fastfood', 240, 11, 24, 11, ['crepe', 350], { tags: ['gluten', 'poultry', 'dairy', 'egg'] }),
  O('crepe-cheese', 'Crepe with mixed cheese', 'كريب ميكس جبن', 'fastfood', 250, 10, 26, 12, ['crepe', 280], { tags: ['gluten', 'dairy', 'egg'], ...V }),
  O('crepe-hotdog', 'Crepe with hot dog and cheese', 'كريب هوت دوج', 'fastfood', 260, 9, 25, 14, ['crepe', 300], { tags: ['gluten', 'meat', 'dairy', 'egg'] }),
  O('quesadilla', 'Chicken quesadilla', 'كاساديا فراخ', 'fastfood', 260, 14, 22, 13, ['quesadilla', 250], { tags: ['gluten', 'poultry', 'dairy'] }),
  O('burrito', 'Burrito (chicken or beef)', 'بوريتو', 'fastfood', 200, 9, 24, 7, ['burrito', 300], { tags: ['gluten', 'dairy'] }),
  O('tacos', 'Tacos (beef or chicken)', 'تاكو', 'fastfood', 220, 10, 18, 12, ['taco', 100], { tags: ['gluten', 'dairy'] }),
  O('nachos', 'Nachos with cheese', 'ناتشوز بالجبنة', 'fastfood', 306, 8, 32, 17, ['portion', 200], { tags: ['dairy'], ...V }),

  // ---------------------------------------------------------------- pizza & feteer
  O('pizza-bbq-chicken', 'Pizza, BBQ chicken', 'بيتزا باربكيو فراخ', 'fastfood', 255, 12.5, 31, 9, ['slice', 115], { tags: ['gluten', 'dairy', 'poultry'], m: PIZZA(320, 690, 920) }),
  O('pizza-ranch', 'Pizza, chicken ranch', 'بيتزا تشيكن رانش', 'fastfood', 270, 12, 28, 12.5, ['slice', 115], { tags: ['gluten', 'dairy', 'poultry', 'egg'], m: PIZZA(320, 690, 920) }),
  O('pizza-vegetable', 'Pizza, vegetable', 'بيتزا خضار', 'fastfood', 235, 10, 30, 8.5, ['slice', 115], { tags: ['gluten', 'dairy'], ...V, m: PIZZA(320, 690, 920) }),
  O('pizza-four-cheese', 'Pizza, four cheese', 'بيتزا فور تشيز', 'fastfood', 290, 13.5, 29, 13.5, ['slice', 110], { tags: ['gluten', 'dairy'], ...V, m: PIZZA(310, 660, 880) }),
  O('pizza-seafood', 'Pizza, seafood', 'بيتزا سي فود', 'fastfood', 240, 12, 29, 8.5, ['slice', 115], { tags: ['gluten', 'dairy', 'seafood', 'fish'], m: PIZZA(320, 690, 920) }),
  O('pizza-sausage', 'Pizza, beef sausage', 'بيتزا سجق', 'fastfood', 285, 12, 30, 13, ['slice', 115], { tags: ['gluten', 'dairy', 'meat'], m: PIZZA(320, 690, 920) }),
  O('pizza-hawaiian', 'Pizza, Hawaiian (turkey ham and pineapple)', 'بيتزا هاواي', 'fastfood', 245, 11, 30, 9, ['slice', 115], { tags: ['gluten', 'dairy', 'poultry'], m: PIZZA(320, 690, 920) }),
  O('pizza-stuffed-crust', 'Pizza, stuffed crust', 'بيتزا أطراف محشية', 'fastfood', 290, 13, 31, 12.5, ['slice', 130], { tags: ['gluten', 'dairy'], ...V, m: PIZZA(360, 780, 1040) }),
  O('pizza-thin', 'Pizza, thin crust (cheese)', 'بيتزا رفيعة', 'fastfood', 280, 12.5, 27, 13.5, ['slice', 80], { tags: ['gluten', 'dairy'], ...V, m: PIZZA(230, 480, 640) }),
  O('pizza-pan', 'Pan pizza, thick crust', 'بيتزا بان', 'fastfood', 280, 11.5, 31, 12, ['slice', 125], { tags: ['gluten', 'dairy'], ...V, m: PIZZA(350, 750, 1000) }),
  O('calzone', 'Calzone', 'كالزوني', 'fastfood', 260, 11, 30, 11, ['calzone', 300], { tags: ['gluten', 'dairy'] }),
  O('feteer-cheese', 'Feteer with cheese', 'فطير جبنة', 'fastfood', 330, 10, 30, 19, ['quarter feteer', 150], { tags: ['gluten', 'dairy'], ...V, m: FETEER }),
  O('feteer-meat', 'Feteer with minced meat or sausage', 'فطير لحمة مفرومة', 'fastfood', 340, 11, 28, 21, ['quarter feteer', 150], { tags: ['gluten', 'meat', 'dairy'], m: FETEER }),
  O('feteer-mix', 'Feteer, mixed (pizza style)', 'فطير ميكس', 'fastfood', 320, 11, 30, 17, ['quarter feteer', 150], { tags: ['gluten', 'dairy', 'meat'], m: FETEER }),
  O('feteer-sweet', 'Feteer, sweet (sugar, custard or honey)', 'فطير حلو', 'sweets', 360, 6, 42, 19, ['quarter feteer', 150], { tags: ['gluten', 'dairy'], ...V, m: FETEER }),

  // ---------------------------------------------------------------- pasta & international plates
  O('mac-cheese', 'Macaroni and cheese', 'ماك آند تشيز', 'meals', 164, 7, 17, 7.5, ['cup', 200], { tags: ['gluten', 'dairy'], ...V }),
  O('pasta-pink', 'Pasta in pink sauce with chicken', 'مكرونة بينك صوص', 'meals', 175, 8.5, 18, 7.5, ['plate', 350], { tags: ['gluten', 'dairy', 'poultry'] }),
  O('pasta-shrimp', 'Shrimp pasta (cream sauce)', 'مكرونة جمبري', 'meals', 170, 8, 17, 7.5, ['plate', 350], { tags: ['gluten', 'dairy', 'seafood'] }),
  O('spaghetti-meatballs', 'Spaghetti with meatballs', 'سباجيتي بكرات اللحم', 'meals', 160, 8, 18, 6, ['plate', 350], { tags: ['gluten', 'meat'] }),
  O('chicken-stroganoff', 'Chicken stroganoff', 'استروجانوف فراخ', 'meals', 150, 12, 6, 9, ['portion', 250], { tags: ['poultry', 'dairy'] }),
  O('chicken-curry', 'Chicken curry', 'كاري فراخ', 'meals', 140, 12, 6, 7.5, ['portion', 250], { tags: ['poultry', 'dairy'] }),
  O('chicken-biryani', 'Chicken biryani', 'برياني فراخ', 'meals', 165, 9, 20, 5.5, ['plate', 400], { tags: ['poultry', 'dairy'] }),
  O('chicken-teriyaki', 'Chicken teriyaki with rice', 'تشيكن ترياكي', 'meals', 150, 9, 20, 3.5, ['plate', 400], { tags: ['poultry', 'soy', 'gluten'] }),
  O('sweet-sour-chicken', 'Sweet and sour chicken (fried)', 'فراخ سويت آند ساور', 'meals', 220, 10, 24, 9, ['portion', 300], { tags: ['poultry', 'gluten', 'egg'] }),
  O('chicken-noodles', 'Chicken noodles, stir-fried', 'نودلز بالفراخ', 'meals', 160, 8, 20, 5.5, ['plate', 350], { tags: ['poultry', 'gluten', 'soy', 'egg'] }),
  O('cordon-bleu', 'Chicken cordon bleu', 'كوردون بلو', 'meals', 250, 18, 12, 14, ['piece', 160], { tags: ['poultry', 'dairy', 'gluten', 'egg'] }),
  O('fish-fillet-pane', 'Breaded fish fillet, fried', 'فيليه سمك بانيه', 'meals', 220, 14, 16, 11, ['fillet', 130], { tags: ['fish', 'gluten', 'egg'] }),

  // ---------------------------------------------------------------- Egyptian home & restaurant dishes
  O('roz-khalta', 'Rice with nuts, liver and minced meat (roz bel khalta)', 'رز بالخلطة', 'meals', 200, 6, 26, 8, ['cup', 160], { tags: ['nuts', 'meat'] }),
  O('spinach-meat', 'Spinach stew with meat', 'سبانخ باللحمة', 'meals', 90, 6, 5, 5, ['bowl', 250], { tags: ['meat'] }),
  O('colocasia', 'Colocasia stew (qolqas)', 'قلقاس', 'meals', 95, 3, 12, 4, ['bowl', 250], V),
  O('torly', 'Mixed vegetable tray (torly)', 'تورلي', 'meals', 85, 2, 9, 5, ['portion', 250], V),
  O('chicken-potato-tray', 'Chicken and potato tray (oven)', 'صينية فراخ بالبطاطس', 'meals', 140, 11, 9, 7, ['portion', 350], { tags: ['poultry'] }),
  O('daoud-basha', 'Meatballs in tomato sauce (daoud basha)', 'داود باشا', 'meals', 160, 9, 9, 10, ['portion', 300], { tags: ['meat', 'gluten'] }),
  O('hamam-mahshi', 'Stuffed pigeon (hamam mahshi)', 'حمام محشي', 'meals', 250, 14, 14, 15, ['pigeon', 300], { tags: ['poultry', 'gluten'] }),
  O('duck-roast', 'Duck, roasted with skin', 'بط محمر', 'meals', 337, 19, 0, 28.4, ['quarter duck', 250], { tags: ['poultry'] }),
  O('warak-enab', 'Stuffed vine leaves (warak enab)', 'ورق عنب', 'meals', 160, 2.8, 19, 8, ['piece', 15], { ...V, m: [M('plate', 'plates', 250)] }),
  O('mahshi-cabbage', 'Stuffed cabbage rolls (mahshi kromb)', 'محشي كرنب', 'meals', 150, 3, 22, 5.5, ['roll', 35], { ...V, m: [M('plate', 'plates', 300)] }),
  O('fatta-chicken', 'Fatta with chicken', 'فتة بالفراخ', 'meals', 200, 10, 21, 8.5, ['plate', 400], { tags: ['poultry', 'gluten'] }),
  O('kaware3', 'Trotters (kaware3)', 'كوارع', 'meals', 200, 20, 0, 13, ['bowl', 250], { tags: ['meat', 'organ'] }),
  O('mixed-grill', 'Mixed grill (kofta, kebab, tawook)', 'مشويات مشكلة', 'meals', 220, 22, 2, 14, ['plate', 300], { tags: ['meat', 'poultry'], m: [M('quarter kilo', 'quarter kilos', 250)] }),
  O('tarb', 'Tarb (kofta wrapped in fat)', 'طرب', 'meals', 350, 16, 2, 31, ['piece', 50], { tags: ['meat'] }),
  O('feseekh', 'Feseekh (salted fermented mullet)', 'فسيخ', 'meals', 200, 25, 0, 11, ['portion', 100], { tags: ['fish'] }),
  O('fish-sayadeya', 'Fish sayadeya (fish with brown rice)', 'سمك صيادية', 'meals', 165, 11, 18, 5, ['plate', 400], { tags: ['fish'] }),
  O('shrimp-rice', 'Shrimp with rice (restaurant)', 'جمبري بالأرز', 'meals', 160, 9, 22, 4, ['plate', 400], { tags: ['seafood'] }),
  O('fish-tagine', 'Fish or shrimp tagine (tomato sauce, baked)', 'طاجن سمك', 'meals', 130, 11, 5, 7.5, ['portion', 300], { tags: ['fish', 'seafood'] }),
  O('eggah', 'Eggah (baked egg and herb omelette)', 'عجة', 'meals', 200, 10, 4, 16, ['slice', 100], { tags: ['egg', 'gluten'], ...V }),
  O('potatoes-fried-home', 'Fried potatoes, home (shibsy)', 'بطاطس محمرة بيتي', 'meals', 260, 3, 30, 14.5, ['plate', 200], V),
  O('potato-stew', 'Potato stew with meat', 'بطاطس باللحمة', 'meals', 120, 6, 11, 6, ['bowl', 300], { tags: ['meat'] }),
  O('kishk', 'Kishk (yogurt and wheat, with chicken)', 'كشك', 'meals', 140, 7, 14, 6, ['bowl', 250], { tags: ['dairy', 'gluten', 'poultry'] }),
  O('kabsa-meat', 'Meat with rice (kabsa or mandi)', 'كبسة لحمة', 'meals', 190, 10, 18, 9, ['plate', 450], { tags: ['meat'] }),
  O('kebda-portion', 'Fried liver, Alexandrian (kebda), portion', 'كبدة إسكندراني', 'meals', 200, 22, 6, 10, ['portion', 150], { tags: ['meat', 'organ'] }),
  O('fried-chicken-home', 'Fried chicken, home (floured)', 'فراخ محمرة', 'meals', 250, 24, 6, 14.5, ['piece', 150], { tags: ['poultry', 'gluten'] }),
  O('chicken-pasta-bechamel', 'Chicken pasta with béchamel (baked)', 'مكرونة بشاميل بالفراخ', 'meals', 175, 9, 16, 8, ['piece', 250], { tags: ['poultry', 'gluten', 'dairy'] }),

  // ---------------------------------------------------------------- breakfast & bakery
  O('french-toast', 'French toast', 'فرنش توست', 'bakery', 229, 7.7, 25, 11, ['slice', 65], { tags: ['gluten', 'egg', 'dairy'], ...V }),
  O('waffle-plain', 'Waffle, plain', 'وافل سادة', 'bakery', 291, 7.9, 33, 14, ['waffle', 75], { tags: ['gluten', 'egg', 'dairy'], ...V }),
  O('bagel', 'Bagel, plain', 'بيجل', 'bakery', 257, 10, 50, 1.6, ['bagel', 100], { tags: ['gluten'], ...V }),
  O('croissant-zaatar', 'Za\'atar croissant', 'كرواسون زعتر', 'bakery', 400, 8, 40, 23, ['croissant', 80], { tags: ['gluten', 'dairy', 'sesame'], ...V }),
  O('croissant-turkey', 'Croissant with turkey and cheese', 'كرواسون تيركي وجبنة', 'bakery', 330, 12, 30, 18, ['croissant', 120], { tags: ['gluten', 'dairy', 'poultry'] }),
  O('croissant-packaged', 'Packaged croissant (Molto type)', 'مولتو', 'snacks', 420, 7, 49, 22, ['croissant', 62], { tags: ['gluten', 'dairy', 'egg'], ...V, m: [M('mini croissant', 'mini croissants', 30)] }),
  O('cupcake', 'Cupcake with frosting', 'كب كيك', 'sweets', 375, 3.5, 57, 15.5, ['cupcake', 70], { tags: ['gluten', 'dairy', 'egg'], ...V }),
  O('swiss-roll', 'Swiss roll', 'سويسرول', 'sweets', 370, 5, 55, 14, ['slice', 40], { tags: ['gluten', 'dairy', 'egg'], ...V }),
  O('plain-cake', 'Plain cake (kika)', 'كيكة سادة', 'sweets', 390, 5.5, 53, 17.5, ['slice', 60], { tags: ['gluten', 'dairy', 'egg'], ...V }),
  O('eclair', 'Éclair', 'إكلير', 'sweets', 262, 6.4, 24, 16, ['eclair', 70], { tags: ['gluten', 'dairy', 'egg'], ...V }),
  O('mille-feuille', 'Mille-feuille', 'ميل فوي', 'sweets', 340, 5, 38, 19, ['piece', 100], { tags: ['gluten', 'dairy', 'egg'], ...V }),
  O('gateau', 'Cream cake slice (gateau)', 'جاتوه', 'sweets', 330, 4.5, 40, 17, ['piece', 90], { tags: ['gluten', 'dairy', 'egg'], ...V }),
  O('fruit-tart', 'Fruit tart', 'تارت فواكه', 'sweets', 280, 4, 36, 13, ['tart', 100], { tags: ['gluten', 'dairy', 'egg'], ...V }),
  O('brioche', 'Brioche bun', 'بريوش', 'bakery', 360, 9, 50, 13.5, ['bun', 60], { tags: ['gluten', 'dairy', 'egg'], ...V }),
  O('pancake-syrup', 'Pancake or maple syrup', 'شراب بان كيك', 'basics', 260, 0, 65, 0.1, ['tbsp', 20], V),
  O('bake-rolz', 'Baked bread chips (Bake Rolz type)', 'بيك رولز', 'snacks', 450, 10, 68, 15, ['small bag', 35], { tags: ['gluten'], ...V }),
  O('date-biscuits', 'Date-filled biscuits (agwa)', 'بسكويت بالعجوة', 'sweets', 420, 5, 66, 15, ['piece', 25], { tags: ['gluten'], ...V }),
  O('lotus-biscuits', 'Caramelised biscuits (Lotus type)', 'بسكويت لوتس', 'sweets', 484, 4.9, 72.6, 19, ['biscuit', 7.8], { tags: ['gluten'], ...V, m: [M('pack of 2', 'packs of 2', 15.6)] }),
  O('wafers-cream', 'Cream-filled wafers (vanilla or chocolate)', 'ويفر بالكريمة', 'sweets', 520, 5, 65, 26, ['small pack', 35], { tags: ['gluten', 'dairy'], ...V }),
  O('cheese-crackers', 'Cheese crackers', 'بسكويت بالجبنة', 'snacks', 490, 10, 60, 23, ['small pack', 35], { tags: ['gluten', 'dairy'], ...V }),

  // ---------------------------------------------------------------- chocolate, candy & desserts
  O('nougat-bar', 'Chocolate bar with nougat and caramel (Mars type)', 'شوكولاتة مارس', 'sweets', 449, 4.2, 70, 17, ['bar', 51], { tags: ['dairy', 'egg'], ...V }),
  O('coconut-bar', 'Coconut chocolate bar (Bounty type)', 'شوكولاتة باونتي', 'sweets', 487, 3.7, 58, 26, ['bar', 57], { tags: ['dairy'], ...V, m: [M('single piece', 'single pieces', 28.5)] }),
  O('caramel-cookie-bar', 'Caramel cookie bar (Twix type)', 'شوكولاتة تويكس', 'sweets', 495, 4.5, 64, 24, ['bar', 50], { tags: ['gluten', 'dairy'], ...V, m: [M('single finger', 'single fingers', 25)] }),
  O('white-chocolate', 'White chocolate', 'شوكولاتة بيضاء', 'sweets', 539, 5.9, 59, 32, ['bar', 40], { tags: ['dairy'], ...V }),
  O('hazelnut-chocolate', 'Milk chocolate with hazelnuts', 'شوكولاتة بالبندق', 'sweets', 550, 8, 52, 34, ['bar', 45], { tags: ['dairy', 'nuts'], ...V }),
  O('marshmallows', 'Marshmallows', 'مارشميلو', 'sweets', 318, 1.8, 81, 0.2, ['piece', 7], {}),
  O('malban', 'Turkish delight (malban)', 'ملبن', 'sweets', 350, 0.5, 87, 0.2, ['piece', 15], V),
  O('sudaniya', 'Peanut brittle (sudaniya)', 'سودانية', 'sweets', 490, 12, 55, 25, ['piece', 25], { tags: ['peanut'], ...V }),
  O('semsemia', 'Sesame brittle (semsemia)', 'سمسمية', 'sweets', 500, 12, 50, 28, ['piece', 25], { tags: ['sesame'], ...V }),
  O('cotton-candy', 'Cotton candy (ghazl el-banat)', 'غزل البنات', 'sweets', 390, 0, 98, 0, ['stick', 30], V),
  O('konafa-filled', 'Konafa with chocolate or cream filling', 'كنافة بالنوتيلا', 'sweets', 430, 6, 48, 24, ['piece', 150], { tags: ['gluten', 'dairy', 'nuts'], ...V }),
  O('konafa-mango', 'Konafa with mango and cream', 'كنافة بالمانجا', 'sweets', 300, 4.5, 38, 14.5, ['piece', 150], { tags: ['gluten', 'dairy'], ...V }),
  O('qatayef-cream', 'Qatayef with cream', 'قطايف بالقشطة', 'sweets', 260, 5, 36, 11, ['piece', 60], { tags: ['gluten', 'dairy'], ...V }),
  O('chocolate-pudding', 'Chocolate pudding', 'بودينج شوكولاتة', 'sweets', 130, 3, 21, 4, ['cup', 120], { tags: ['dairy'], ...V }),
  O('chocolate-mousse', 'Chocolate mousse', 'موس شوكولاتة', 'sweets', 260, 4.5, 22, 17.5, ['cup', 100], { tags: ['dairy', 'egg'], ...V }),
  O('frozen-yogurt', 'Frozen yogurt', 'فروزن يوجرت', 'sweets', 140, 3.5, 24, 4, ['cup', 150], { tags: ['dairy'], ...V }),
  O('ice-lolly', 'Ice lolly (fruit ice)', 'آيس كريم مصاصة', 'sweets', 75, 0, 19, 0, ['stick', 60], V),
  O('ice-cream-sandwich', 'Ice cream sandwich', 'آيس كريم ساندوتش', 'sweets', 240, 4.5, 37, 9, ['piece', 70], { tags: ['dairy', 'gluten'], ...V }),
  O('ice-cream-cone-pack', 'Ice cream cone, packaged (Cornetto type)', 'آيس كريم كورنيتو', 'sweets', 290, 4, 34, 15, ['cone', 75], { tags: ['dairy', 'gluten'], ...V }),
  O('mcflurry-style', 'Soft-serve with cookie pieces (McFlurry style)', 'ماك فلري', 'sweets', 179, 4.2, 28, 5.6, ['cup', 285], { tags: ['dairy', 'gluten'], ...V }),
  O('sundae', 'Sundae, chocolate or caramel', 'صنداي', 'sweets', 184, 4.5, 30, 5.6, ['cup', 179], { tags: ['dairy'], ...V }),
  O('soft-serve-cone', 'Soft-serve ice cream cone', 'آيس كريم كون', 'sweets', 167, 4, 26, 5, ['cone', 90], { tags: ['dairy', 'gluten'], ...V }),
  O('churros', 'Churros', 'تشوروز', 'sweets', 380, 5, 42, 22, ['piece', 30], { tags: ['gluten', 'egg', 'dairy'], ...V }),

  // ---------------------------------------------------------------- snacks & cereals
  O('stacked-chips', 'Stacked potato crisps (Pringles type)', 'برينجلز', 'snacks', 527, 4.6, 53, 33, ['serving (about 16)', 28], { ...V, m: [M('small can', 'small cans', 40), M('large can', 'large cans', 165)] }),
  O('popcorn-caramel', 'Popcorn, caramel', 'فشار بالكراميل', 'snacks', 400, 3.5, 78, 9, ['small bag', 40], V),
  O('peanuts-salted', 'Peanuts, roasted and salted', 'سوداني مملح', 'snacks', 590, 24, 21, 50, ['handful', 30], { tags: ['peanut'], ...V }),
  O('chocolate-cereal', 'Chocolate cereal (Coco Pops type)', 'سيريال شوكولاتة', 'snacks', 387, 5, 86, 2.6, ['bowl (dry)', 40], V),
  O('frosted-flakes', 'Frosted corn flakes', 'كورن فليكس بالسكر', 'snacks', 375, 4.2, 89, 0.5, ['bowl (dry)', 40], V),
  O('honey-cereal', 'Honey loops cereal', 'سيريال بالعسل', 'snacks', 375, 7.5, 78, 3.5, ['bowl (dry)', 40], { tags: ['gluten'], ...V }),

  // ---------------------------------------------------------------- drinks
  O('energy-drink-zero', 'Energy drink, sugar-free', 'مشروب طاقة بدون سكر', 'drinks', 3, 0, 0.5, 0, ['can', 250], V),
  O('flat-white', 'Flat white', 'فلات وايت', 'drinks', 50, 3.1, 4, 2.5, ['cup', 240], { tags: ['dairy'], ...V }),
  O('chai-latte', 'Chai tea latte', 'شاي لاتيه', 'drinks', 79, 2.4, 13, 1.9, ['medium cup', 350], { tags: ['dairy'], ...V }),
  O('iced-latte', 'Iced latte, no sugar', 'آيس لاتيه', 'drinks', 40, 2.3, 3.3, 2, ['medium cup', 400], { tags: ['dairy'], ...V }),
  O('iced-mocha', 'Iced mocha', 'آيس موكا', 'drinks', 75, 2.3, 11, 2.5, ['medium cup', 400], { tags: ['dairy'], ...V }),
  O('fruit-milk', 'Fruit with milk (banana, strawberry or mango)', 'موز باللبن', 'drinks', 80, 3, 12.5, 2.3, ['glass', 350], { tags: ['dairy'], ...V }),
  O('lemonade', 'Lemonade, sweetened', 'ليموناضة', 'drinks', 40, 0.1, 10.5, 0, ['glass', 300], V),
  O('cantaloupe-juice', 'Cantaloupe juice', 'عصير كانتالوب', 'drinks', 45, 0.6, 11, 0.2, ['glass', 350], V),
  O('watermelon-juice', 'Watermelon juice', 'عصير بطيخ', 'drinks', 35, 0.5, 8.5, 0.1, ['glass', 350], V),
  O('apple-juice', 'Apple juice', 'عصير تفاح', 'drinks', 46, 0.1, 11.3, 0.1, ['glass', 250], V),
  O('pomegranate-juice', 'Pomegranate juice', 'عصير رمان', 'drinks', 54, 0.2, 13, 0.3, ['glass', 250], V),
  O('carrot-juice', 'Carrot or carrot-orange juice', 'عصير جزر', 'drinks', 40, 0.9, 9.3, 0.2, ['glass', 300], V),
  O('coconut-water', 'Coconut water', 'مياه جوز الهند', 'drinks', 19, 0.7, 3.7, 0.2, ['bottle', 330], V),
  O('hot-milk-honey', 'Hot milk with honey or cinnamon', 'لبن سخن بالعسل', 'drinks', 85, 3.2, 11, 3, ['mug', 250], { tags: ['dairy'], ...V }),
  O('karak-tea', 'Karak tea (sweet milk tea)', 'شاي كرك', 'drinks', 75, 2, 11, 2.5, ['cup', 200], { tags: ['dairy'], ...V }),

  // ---------------------------------------------------------------- sauces & spreads
  O('ranch', 'Ranch dressing', 'صوص رانش', 'basics', 430, 1, 6, 45, ['tbsp', 15], { tags: ['egg', 'dairy'], ...V }),
  O('thousand-island', 'Thousand Island dressing', 'صوص ثاوزند آيلاند', 'basics', 370, 1, 15, 34, ['tbsp', 16], { tags: ['egg'], ...V }),
  O('honey-mustard', 'Honey mustard sauce', 'صوص هاني ماستارد', 'basics', 270, 1, 30, 16, ['tbsp', 15], { tags: ['egg'], ...V }),
  O('cheese-sauce', 'Cheese sauce (nacho)', 'صوص جبنة', 'basics', 200, 5, 8, 16.5, ['tbsp', 17], { tags: ['dairy'], ...V }),
  O('chocolate-syrup', 'Chocolate syrup', 'صوص شوكولاتة', 'basics', 279, 2.1, 65, 1.1, ['tbsp', 19], V),
  O('caramel-sauce', 'Caramel sauce', 'صوص كراميل', 'basics', 330, 1.5, 63, 8, ['tbsp', 20], { tags: ['dairy'], ...V }),
  O('whipped-cream', 'Whipped cream (spray)', 'كريمة شانتيه', 'basics', 257, 3.2, 12.5, 22, ['serving', 10], { tags: ['dairy'], ...V }),
  O('tomato-paste', 'Tomato paste (salsa)', 'صلصة طماطم', 'basics', 82, 4.3, 16, 0.5, ['tbsp', 16], V),
  O('margarine', 'Margarine', 'سمنة نباتي', 'basics', 717, 0.2, 0.7, 80, ['tsp', 5], { ...V, m: [M('tbsp', 'tbsp', 14)] }),
  O('lotus-spread', 'Caramelised biscuit spread (Lotus type)', 'لوتس دهن', 'basics', 584, 2.7, 57, 38, ['tbsp', 15], { tags: ['gluten'], ...V }),
];

/**
 * Words people type that are not in a food's name: chain and brand names, and other names for
 * the same thing. Search only (search.js); the app never shows them.
 */
export const SEARCH_KEYWORDS = {
  'big-mac-style': 'big mac bigmac mcdonalds macdonalds mac',
  'quarter-pounder': 'mcroyale quarter pounder qpc mcdonalds macdonalds',
  'mcchicken-style': 'mcchicken mcdonalds macdonalds',
  'fish-burger': 'filet o fish fillet mcfish mcdonalds',
  'egg-muffin': 'mcmuffin mcdonalds breakfast',
  'hash-brown': 'hashbrown mcdonalds',
  'apple-pie-ff': 'mcdonalds',
  'mcflurry-style': 'mcflurry mcdonalds oreo',
  sundae: 'mcdonalds',
  'whopper-style': 'whopper burger king bk',
  'chicken-royale': 'chicken royale burger king bk',
  zinger: 'zinger kfc kentucky',
  twister: 'twister kfc kentucky',
  'kfc-original': 'kfc kentucky original',
  'popcorn-chicken': 'kfc kentucky',
  rizo: 'rizo kfc kentucky',
  'mashed-potato-gravy': 'kfc kentucky',
  coleslaw: 'kfc kentucky',
  'famous-star': 'hardees hardee famous star super star',
  'mushroom-swiss': 'hardees hardee',
  'smash-burger': 'smashed buffalo burger',
  'sub-chicken': 'subway sub',
  'sub-tuna': 'subway sub',
  'chicken-nuggets': 'mcnuggets mcdonalds kfc nugget',
  'nuggets-frozen': 'nugget',
  fries: 'chips mcdonalds kfc',
  'pizza-pan': 'pizza hut',
  'pizza-stuffed-crust': 'pizza hut dominos',
  'pizza-margherita': 'dominos pizza hut papa johns',
  'pizza-pepperoni': 'dominos pizza hut papa johns',
  'shawarma-arabi': 'arabic shawerma',
  'croissant-packaged': 'molto',
  'cake-bar': 'todo twinkies',
  'cream-biscuits': 'oreo borio',
  'wafer-chocolate': 'kitkat kit kat',
  'caramel-nut-bar': 'snickers',
  'milk-chocolate': 'galaxy cadbury dairy milk',
  'nougat-bar': 'mars',
  'coconut-bar': 'bounty',
  'caramel-cookie-bar': 'twix',
  'chocolate-spread': 'nutella',
  'potato-chips': 'lays chipsy',
  'stacked-chips': 'pringles',
  'cheese-puffs': 'cheetos kranshy',
  'tortilla-chips': 'doritos',
  'bake-rolz': 'bake rolz rolls',
  'lotus-biscuits': 'lotus biscoff',
  'lotus-spread': 'lotus biscoff',
  'ice-cream-cone-pack': 'cornetto',
  'energy-drink': 'red bull redbull monster sting power horse',
  'energy-drink-zero': 'red bull redbull monster zero sugar free',
  'fizzy-drink': 'sprite 7up seven up fanta mirinda',
  cola: 'pepsi coke coca',
  'diet-cola': 'pepsi coke coca zero',
  'malt-drink': 'fayrouz birell',
  'nescafe-3in1': 'nescafe',
  'chocolate-cereal': 'coco pops',
  'frosted-flakes': 'frosties',
  'fruit-milk': 'banana milk strawberry milk mango milk',
  'instant-noodles': 'indomie noodles',
};

